name: WilderBlog-Build

on: 
  push:
    branches:
      master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: NPM Tasks
      working-directory: ./src/WilderBlog      
      run: |
        npm install
        node node_modules/gulp/bin/gulp.js
    - name: Vue Build
      working-directory: ./src/WilderBlog/client
      run: |
        npm install
        npm install @vue/cli
        npm run build
    - name: Build Project
      working-directory: ./src/WilderBlog      
      run: dotnet build --configuration Release
    - name: Run Tests
      working-directory: ./src/WilderBlog.Tests      
      run: dotnet test
